"""Generate the synthetic example packages under examples/.

Everything here is computed from simple formulas: no real-world data, no
third-party assets, no randomness. Run:

    uv run python scripts/generate_examples.py          # regenerate in place
    uv run python scripts/generate_examples.py --check  # verify committed examples are current

--check compares decoded pixels and JSON content (ignoring SHA-256 values,
which depend on the zlib build), so it is stable across platforms.
"""

from __future__ import annotations

import argparse
import copy
import json
import shutil
import sys
import tempfile
import warnings
import zipfile
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from world_map_interchange import geometry  # noqa: E402
from world_map_interchange import png as pngmod  # noqa: E402
from world_map_interchange import scalar as scalarmod  # noqa: E402
from world_map_interchange.bundle import dump_json, pack, sha256_bytes, sidecar_for  # noqa: E402

CREATED = "2026-10-05T12:00:00Z"
PRODUCER = {"name": "wmi-example-generator", "version": "0.1.0"}
LICENSE = "MIT"
ATTRIBUTION = "Synthetic example generated by scripts/generate_examples.py in the world-map-interchange repository."

WORLD = {
    "id": "example:synthetic-world-a",
    "name": "Synthetic World A (fictional)",
    "description": "A fictional planet built from analytic formulas for testing. It is not Earth.",
    "body": {"shape": "sphere", "radius_m": 5200000.0},
    "sea_level_description": "Mean sea level at the snapshot. Elevation with datum 'sea_level' is 0 m at sea level.",
}

ASTER = {
    "kind": "fixed",
    "description": "Fictional calendar of Synthetic World A: 400 local days of 28 SI hours, in five unequal named periods.",
    "day_length_s": 100800,
    "year_length_days": 400,
    "periods": [
        {"id": "thaw", "label": "Thaw", "length_days": 70},
        {"id": "bloom", "label": "Bloom", "length_days": 110},
        {"id": "highsun", "label": "High Sun", "length_days": 60},
        {"id": "harvest", "label": "Harvest", "length_days": 90},
        {"id": "deepcold", "label": "Deep Cold", "length_days": 70},
    ],
    "leap_rule": "No leap days.",
}

CLIMATOLOGY_SPAN = {"start": {"year": 1}, "end": {"year": 30}}


def climatology(steps, label):
    return {"calendar": "aster", "label": label, "span": copy.deepcopy(CLIMATOLOGY_SPAN), "aggregation": steps, "timestep_s": 25200}


ANNUAL_MEAN = [{"statistic": "mean", "over": "timesteps", "within": "year"}, {"statistic": "mean", "over": "years"}]
MEAN_ANNUAL_MIN = [{"statistic": "minimum", "over": "timesteps", "within": "year"}, {"statistic": "mean", "over": "years"}]
MEAN_ANNUAL_MAX = [{"statistic": "maximum", "over": "timesteps", "within": "year"}, {"statistic": "mean", "over": "years"}]
COLDEST_PERIOD_MEAN = [
    {"statistic": "mean", "over": "timesteps", "within": "period"},
    {"statistic": "mean", "over": "years"},
    {"statistic": "minimum", "over": "periods"},
]
ANNUAL_TOTAL = [{"statistic": "sum", "over": "timesteps", "within": "year"}, {"statistic": "mean", "over": "years"}]
WETTEST_PERIOD_TOTAL = [
    {"statistic": "sum", "over": "timesteps", "within": "period"},
    {"statistic": "mean", "over": "years"},
    {"statistic": "maximum", "over": "periods"},
]


# ------------------------------------------------------------------ synthetic fields


def mesh(grid):
    lats, lons = geometry.centres(grid, normalize=False)
    lon2, lat2 = np.meshgrid(np.radians(lons), np.radians(lats))
    return lat2, lon2


def elevation_field(lat, lon):
    e = (
        3200 * np.sin(2 * lon + 0.6) * np.cos(lat) ** 0.6
        + 1400 * np.cos(3 * lat) * np.sin(3 * lon - 0.4)
        + 900 * np.sin(5 * lon) * np.sin(4 * lat)
        - 900
    )
    return np.round(e, 3)


def temperature_mean_c(lat, elev):
    sea_level = 27.0 - 52.0 * np.sin(lat) ** 2
    return sea_level - 0.0065 * np.maximum(elev, 0.0), sea_level


def precipitation_total_mm(lat, lon):
    p = 300 + 1900 * np.exp(-((lat / 0.22) ** 2)) + 700 * np.cos(2 * lat) * np.sin(2 * lon + 1.0) - 250 * np.cos(4 * lat)
    return np.maximum(np.round(p, 2), 0.0)


def hypsometric(elev):
    stops = [(-8000, (8, 20, 70)), (-200, (60, 120, 200)), (0, (150, 200, 230)), (1, (60, 140, 70)),
             (1500, (190, 170, 90)), (4000, (140, 110, 90)), (6000, (250, 250, 250))]
    xs = np.array([s[0] for s in stops], dtype=float)
    out = np.zeros(elev.shape + (3,), dtype=np.uint8)
    for ch in range(3):
        ys = np.array([s[1][ch] for s in stops], dtype=float)
        out[..., ch] = np.round(np.interp(elev, xs, ys)).astype(np.uint8)
    return out


def colour_bar(width=256, height=24, alpha=True):
    elev = np.linspace(-8000, 6000, width)[None, :].repeat(height, axis=0)
    rgb = hypsometric(elev)
    if not alpha:
        return rgb
    a = np.full((height, width, 1), 255, dtype=np.uint8)
    a[:, :2] = 0
    a[:, -2:] = 0
    return np.concatenate([rgb, a], axis=2)


def hex_to_rgb(h):
    return tuple(int(h[i : i + 2], 16) for i in (1, 3, 5))


# ------------------------------------------------------------------ example builder


class Example:
    def __init__(self, name, title, description, *, world=None, calendars=None, source=None, package_id=None):
        self.name = name
        self.title = title
        self.description = description
        self.world = copy.deepcopy(world or WORLD)
        self.calendars = calendars
        self.source = source
        self.package_id = package_id or f"urn:example:wmi:{name}"
        self.grids: dict = {}
        self.class_tables: dict = {}
        self.layers: list = []
        self.files: dict[str, bytes] = {}
        self.expected: list = []
        self.notes: list = []
        self._arrays: dict = {}

    def grid(self, gid, width, height, west=-180.0, east=180.0, north=90.0, south=-90.0, description=None):
        g = {"type": "lonlat_regular", "width": width, "height": height,
             "bounds": {"west": west, "east": east, "north": north, "south": south}}
        if description:
            g = {"type": "lonlat_regular", "description": description, **{k: v for k, v in g.items() if k != "type"}}
        self.grids[gid] = g
        return mesh(g)

    def class_table(self, tid, taxonomy, classes, title=None, description=None):
        t = {"taxonomy": taxonomy}
        if title:
            t["title"] = title
        if description:
            t["description"] = description
        t["classes"] = classes
        self.class_tables[tid] = t

    def _validity(self, lid, valid, name):
        if valid is None:
            return None
        valid = np.asarray(valid, dtype=bool)
        path = f"masks/{name or lid + '-valid'}.png"
        data = pngmod.write_png(np.where(valid, 255, 0).astype(np.uint8), 8)
        if path in self.files and self.files[path] != data:
            raise ValueError(f"shared validity mask {path} differs")
        self.files[path] = data
        return {"path": path, "sha256": ""}

    def _common(self, layer, title, description, definition, qualifiers, time, source, provenance):
        for key, value in (("title", title), ("description", description), ("definition", definition)):
            if value:
                layer[key] = value
        if qualifiers:
            layer["qualifiers"] = qualifiers
        if time:
            layer["time"] = time
        if source:
            layer["source"] = source
        if provenance:
            layer["provenance"] = provenance

    def scalar(self, lid, quantity, values, units, grid, *, enc=None, valid=None, qualifiers=None, time=None,
               title=None, description=None, definition=None, source=None, provenance=None, validity_name=None,
               statistics=True, samples=None):
        values = np.asarray(values, dtype=np.float64)
        lo, hi = enc if enc else scalarmod.choose_range(values, valid)
        pixels = scalarmod.encode(values, lo, hi, valid)
        path = f"maps/{lid}.png"
        self.files[path] = pngmod.write_png(pixels, 16)
        layer = {"id": lid, "kind": "scalar", "quantity": quantity}
        self._common(layer, title, description, definition, None, None, None, None)
        layer.update({"grid": grid, "path": path, "sha256": "", "units": units,
                      "encoding": {"type": "png16_linear", "min": lo, "max": hi}})
        vm = self._validity(lid, valid, validity_name)
        if vm:
            layer["validity_mask"] = vm
        self._common(layer, None, None, None, qualifiers, time, source, provenance)
        if statistics:
            decoded = scalarmod.decode(pixels, lo, hi)
            stats = scalarmod.statistics(decoded, None if valid is None else np.asarray(valid, bool))
            layer["statistics"] = {k: (round(v, 6) if isinstance(v, float) else v) for k, v in stats.items()}
        self.layers.append(layer)
        self._arrays[lid] = values
        half = scalarmod.quantization_step(lo, hi) / 2
        vmask = np.ones(values.shape, bool) if valid is None else np.asarray(valid, bool)
        for r, c in self._points(values.shape, samples, values, vmask):
            lat, lon = geometry.pixel_centre(self.grids[grid], r, c)
            entry = {"layer": lid, "row": r, "col": c, "lat": round(lat, 6), "lon": round(lon, 6), "valid": bool(vmask[r, c])}
            if vmask[r, c]:
                entry.update({"value": float(values[r, c]), "units": units, "pixel": int(pixels[r, c]), "tolerance": half})
            self.expected.append(entry)

    def categorical(self, lid, quantity, codes, grid, table, *, valid=None, qualifiers=None, time=None, title=None,
                    description=None, source=None, samples=None):
        codes = np.asarray(codes, dtype=np.uint16)
        path = f"maps/{lid}.png"
        self.files[path] = pngmod.write_png(codes, 16)
        layer = {"id": lid, "kind": "categorical", "quantity": quantity}
        self._common(layer, title, description, None, None, None, None, None)
        layer.update({"grid": grid, "path": path, "sha256": "", "encoding": {"type": "png16_codes"}, "class_table": table})
        vm = self._validity(lid, valid, None)
        if vm:
            layer["validity_mask"] = vm
        self._common(layer, None, None, None, qualifiers, time, source, None)
        self.layers.append(layer)
        lookup = {c["code"]: c["id"] for c in self.class_tables.get(table, {"classes": []})["classes"]}
        vmask = np.ones(codes.shape, bool) if valid is None else np.asarray(valid, bool)
        per_class = [tuple(int(x) for x in np.argwhere((codes == k) & vmask)[0]) for k in np.unique(codes[vmask])]
        for r, c in self._points(codes.shape, list(samples or []) + per_class):
            lat, lon = geometry.pixel_centre(self.grids[grid], r, c)
            entry = {"layer": lid, "row": r, "col": c, "lat": round(lat, 6), "lon": round(lon, 6), "valid": bool(vmask[r, c])}
            if vmask[r, c]:
                entry.update({"code": int(codes[r, c]), "class_id": lookup.get(int(codes[r, c]))})
            self.expected.append(entry)

    def mask(self, lid, quantity, truth, grid, *, qualifiers=None, title=None, description=None, samples=None, valid=None):
        truth = np.asarray(truth, dtype=bool)
        path = f"maps/{lid}.png"
        self.files[path] = pngmod.write_png(np.where(truth, 255, 0).astype(np.uint8), 8)
        layer = {"id": lid, "kind": "mask", "quantity": quantity}
        self._common(layer, title, description, None, None, None, None, None)
        layer.update({"grid": grid, "path": path, "sha256": "", "encoding": {"type": "png8_binary"}})
        vm = self._validity(lid, valid, None)
        if vm:
            layer["validity_mask"] = vm
        if qualifiers:
            layer["qualifiers"] = qualifiers
        self.layers.append(layer)
        extra = list(samples or []) + [tuple(int(x) for x in np.argwhere(truth)[0])] if truth.any() else list(samples or [])
        for r, c in self._points(truth.shape, extra):
            lat, lon = geometry.pixel_centre(self.grids[grid], r, c)
            self.expected.append({"layer": lid, "row": r, "col": c, "lat": round(lat, 6), "lon": round(lon, 6),
                                  "valid": True, "mask": bool(truth[r, c])})

    def reference(self, lid, image, role, registration, *, grid=None, depicts=None, title=None, description=None):
        path = f"previews/{lid}.png"
        self.files[path] = pngmod.write_png(image, 8)
        layer = {"id": lid, "kind": "reference"}
        if title:
            layer["title"] = title
        if description:
            layer["description"] = description
        if grid:
            layer["grid"] = grid
        layer.update({"path": path, "sha256": "", "role": role, "registration": registration})
        if depicts:
            layer["depicts"] = depicts
        self.layers.append(layer)

    def raw_layer(self, layer, path, data):
        self.files[path] = data
        self.layers.append(layer)

    @staticmethod
    def _points(shape, extra=None, values=None, valid=None):
        h, w = shape
        pts = [(0, 0), (0, w - 1), (h - 1, 0), (h - 1, w - 1), (h // 2, w // 2), (h // 4, w // 3), (3 * h // 4, 2 * w // 3)]
        if values is not None and valid is not None and valid.any():
            masked = np.where(valid, values, np.nan)
            pts.append(tuple(int(x) for x in np.unravel_index(np.nanargmin(masked), shape)))
            pts.append(tuple(int(x) for x in np.unravel_index(np.nanargmax(masked), shape)))
        pts += list(extra or [])
        seen, out = set(), []
        for p in pts:
            if p not in seen:
                seen.add(p)
                out.append(p)
        return out

    def manifest(self):
        m = {
            "format": "world-map-interchange",
            "format_version": "0.1.0",
            "package": {
                "id": self.package_id,
                "title": self.title,
                "description": self.description,
                "created": CREATED,
                "producer": PRODUCER,
                "license": LICENSE,
                "attribution": ATTRIBUTION,
            },
            "world": self.world,
        }
        if self.source:
            m["source"] = self.source
        if self.calendars:
            m["calendars"] = self.calendars
        m["grids"] = self.grids
        if self.class_tables:
            m["class_tables"] = self.class_tables
        m["layers"] = self.layers
        return m

    def write(self, outdir: Path, *, mutate_before_hash=None, mutate_after_hash=None, sidecars=False, expected=True):
        manifest = copy.deepcopy(self.manifest())
        files = dict(self.files)
        if mutate_before_hash:
            mutate_before_hash(manifest, files)
        for layer in manifest["layers"]:
            if layer.get("path") in files:
                layer["sha256"] = sha256_bytes(files[layer["path"]])
            vm = layer.get("validity_mask")
            if vm and vm["path"] in files:
                vm["sha256"] = sha256_bytes(files[vm["path"]])
        if sidecars:
            for layer in manifest["layers"]:
                if layer["kind"] != "reference":
                    files[layer["path"] + ".json"] = dump_json(sidecar_for(manifest, layer)).encode()
        if mutate_after_hash:
            mutate_after_hash(manifest, files)
        target = outdir / self.name
        target.mkdir(parents=True, exist_ok=True)
        for rel, data in files.items():
            p = target.joinpath(*rel.split("/"))
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(data)
        (target / "manifest.json").write_text(dump_json(manifest), encoding="utf-8", newline="\n")
        if expected:
            doc = {"example": self.name, "title": self.title, "package": f"examples/valid/{self.name}",
                   "notes": self.notes, "samples": self.expected}
            exp_dir = outdir.parent / "expected"
            exp_dir.mkdir(parents=True, exist_ok=True)
            (exp_dir / f"{self.name}.json").write_text(dump_json(doc), encoding="utf-8", newline="\n")
        return target


# ------------------------------------------------------------------ valid examples


def ex_elevation_bathymetry(out):
    ex = Example(
        "elevation-bathymetry",
        "Signed elevation with bathymetry and a known sea level",
        "Full elevation including sea floor, relative to sea level (0 m). Positive-down sea-floor depth, ocean, lake and river masks, "
        "plus a registered colour preview and an unregistered legend.",
        source={"simulation_id": "example-sim-1", "run_id": "run-7", "snapshot_id": "snap-120",
                "simulation_time": {"calendar": "aster", "year": 120, "label": "Year 120 of the example run"},
                "source_heightmap": {"id": "example-heightmap-1", "description": "Analytic heightmap defined in generate_examples.py"}},
        calendars={"aster": ASTER},
    )
    lat, lon = ex.grid("global-128", 128, 64)
    elev = elevation_field(lat, lon)
    ocean = elev < 0
    lake = np.zeros_like(ocean)
    lake[18:21, 70:74] = True
    lake &= ~ocean
    river = np.zeros_like(ocean)
    for c in range(60, 90):
        river[int(round(30 + 6 * np.sin(c / 5.0))), c] = True
    river &= ~ocean & ~lake
    ex.scalar("elevation", "elevation", elev, "m", "global-128", enc=(-8000.0, 6000.0),
              qualifiers={"datum": "sea_level", "coverage": "full", "surface": "top_of_solid_surface", "lake_treatment": "lake_surface"},
              title="Elevation relative to sea level",
              description="Signed: negative values are bathymetry. Encoding range is wider than the observed extrema (see statistics).")
    ex.scalar("sea-floor-depth", "sea_floor_depth", np.where(ocean, -elev, np.nan), "m", "global-128", enc=(0.0, 8000.0),
              valid=ocean, validity_name="ocean-only", title="Sea-floor depth (positive down)")
    ex.mask("ocean", "ocean_mask", ocean, "global-128", qualifiers={"classification": "cell_centre"})
    ex.mask("lakes", "lake_mask", lake, "global-128")
    ex.mask("rivers", "river_mask", river, "global-128", qualifiers={"rasterisation": "Synthetic sinusoidal channel, one cell wide"})
    ex.reference("elevation-preview", hypsometric(elev), "preview", "registered", grid="global-128", depicts=["elevation"],
                 title="Hypsometric colour preview (not numeric data)")
    ex.reference("elevation-legend", colour_bar(), "legend", "unregistered", depicts=["elevation-preview"],
                 title="Colour bar for the preview, -8000 m (left) to 6000 m (right)")
    ex.notes = [
        "Sea level is 0 m (datum 'sea_level'). With encoding -8000..6000 the derived sea-level pixel is "
        f"floor(8000/14000*65535 + 0.5) = {int(scalarmod.encode([0.0], -8000.0, 6000.0)[0])}.",
        "Samples with valid=false in sea-floor-depth are land.",
    ]
    ex.write(out, sidecars=True)


def ex_climate_only(out):
    ex = Example(
        "climate-only",
        "Climate-only export (no height layer)",
        "Temperature statistics and precipitation for a fictional calendar. No elevation layer: a climate-only bundle is valid.",
        calendars={"aster": ASTER},
        source={"simulation_id": "example-climate-sim", "run_id": "clim-run-3",
                "simulation_time": {"calendar": "aster", "year": 30, "label": "End of 30-year climatology"}},
    )
    lat, lon = ex.grid("global-96", 96, 48)
    elev = elevation_field(lat, lon)
    ocean = elev < 0
    tmean, tsea = temperature_mean_c(lat, elev)
    s = np.abs(np.sin(lat))
    trange = (-90.0, 50.0)
    terrain = {"elevation_reference": "terrain", "height_above_surface_m": 2.0}
    ex.scalar("t-annual-mean", "air_temperature", np.round(tmean, 4), "degC", "global-96", enc=trange, qualifiers=terrain,
              time=climatology(ANNUAL_MEAN, "30-year mean of annual means"), title="Annual mean 2 m air temperature")
    ex.scalar("t-annual-min", "air_temperature", np.round(tmean - (8 + 15 * s), 4), "degC", "global-96", enc=trange, qualifiers=terrain,
              time=climatology(MEAN_ANNUAL_MIN, "30-year mean of annual timestep minima"), title="Mean annual minimum (timestep extreme)")
    ex.scalar("t-annual-max", "air_temperature", np.round(tmean + (6 + 10 * s), 4), "degC", "global-96", enc=trange, qualifiers=terrain,
              time=climatology(MEAN_ANNUAL_MAX, "30-year mean of annual timestep maxima"), title="Mean annual maximum (timestep extreme)")
    ex.scalar("t-coldest-period", "air_temperature", np.round(tmean - (4 + 10 * s), 4), "degC", "global-96", enc=trange, qualifiers=terrain,
              time=climatology(COLDEST_PERIOD_MEAN, "Mean temperature of the coldest calendar period"),
              title="Coldest-period mean (extremum of period means)")
    thaw = climatology(ANNUAL_MEAN, "30-year mean of the Thaw period")
    thaw["select_periods"] = ["thaw"]
    ex.scalar("t-thaw-mean", "air_temperature", np.round(tmean - (2 + 6 * s), 4), "degC", "global-96", enc=trange, qualifiers=terrain,
              time=thaw, title="Mean temperature of the Thaw period (single-period climatology)")
    ex.scalar("t-annual-mean-sea-level", "air_temperature", np.round(tsea, 4), "degC", "global-96", enc=trange,
              qualifiers={"elevation_reference": "sea_level_reduced", "height_above_surface_m": 2.0, "lapse_rate_K_per_m": 0.0065},
              time=climatology(ANNUAL_MEAN, "30-year mean of annual means"), title="Annual mean air temperature reduced to sea level")
    sst = np.where(ocean, np.clip(np.round(tsea + 1.0, 4), -1.8, 31.0), np.nan)
    ex.scalar("sst-annual-mean", "sea_surface_temperature", sst, "degC", "global-96", enc=(-2.0, 32.0), valid=ocean,
              validity_name="ocean", time=climatology(ANNUAL_MEAN, "30-year mean of annual means"), title="Annual mean sea-surface temperature")

    total = precipitation_total_mm(lat, lon)
    snow_frac = np.clip((2.0 - tmean) / 12.0, 0.0, 1.0)
    snow = np.round(total * snow_frac, 2)
    rain = np.round(total - snow, 2)
    total = rain + snow
    prange = (0.0, 4000.0)
    t_annual = climatology(ANNUAL_TOTAL, "30-year mean of annual totals")
    ex.scalar("precip-annual", "precipitation_amount", total, "mm", "global-96", enc=prange, time=t_annual,
              title="Mean annual total precipitation (all phases, liquid water equivalent)")
    ex.scalar("rain-annual", "rainfall_amount", rain, "mm", "global-96", enc=prange, time=copy.deepcopy(t_annual),
              title="Mean annual rainfall (liquid only)")
    ex.scalar("snowfall-annual", "snowfall_amount", snow, "mm", "global-96", enc=prange, time=copy.deepcopy(t_annual),
              title="Mean annual snowfall (liquid water equivalent)")
    wettest = np.round(total * (0.30 + 0.15 * np.cos(lon) ** 2), 2)
    ex.scalar("precip-wettest-period", "precipitation_amount", wettest, "mm", "global-96", enc=prange,
              time=climatology(WETTEST_PERIOD_TOTAL, "Mean total of the wettest calendar period"),
              title="Wettest-period precipitation total")
    ex.notes = [
        "Temperatures are in degC and include negative values; the encoding range -90..50 is shared so layers are directly comparable.",
        "rain-annual + snowfall-annual equals precip-annual before quantisation; after decoding they agree within 1.5 quantisation steps.",
        "Where precipitation is exactly 0 mm the sample is valid with pixel 0 (legitimate zero, not missing).",
        "All periods refer to the fictional 'aster' calendar (400 days of 28 h, five unequal periods).",
    ]
    ex.write(out)


def ex_snow_and_soil(out):
    ex = Example(
        "snow-and-soil",
        "Snow and soil moisture with explicit meanings",
        "Snow depth, snow water equivalent, snow-cover fraction, volumetric soil moisture with a declared layer, and a producer-specific model index kept as an extension.",
        calendars={"aster": ASTER},
    )
    lat, lon = ex.grid("global-64", 64, 32)
    elev = elevation_field(lat, lon)
    land = elev >= 0
    tmean, _ = temperature_mean_c(lat, elev)
    cold = np.clip((-tmean) / 30.0, 0.0, 1.0)
    swe = np.round(np.where(land, 900 * cold**1.5, 0.0), 2)
    depth = np.round(swe / 300.0, 4)
    cover = np.round(np.where(land, np.clip(cold * 1.6, 0, 1), np.clip(cold * 0.8, 0, 1)), 4)
    t_max = climatology(MEAN_ANNUAL_MAX, "30-year mean of annual maxima")
    ex.scalar("snow-depth-max", "snow_depth", depth, "m", "global-64", enc=(0.0, 5.0), time=t_max, title="Mean annual maximum snow depth")
    ex.scalar("swe-max", "snow_water_equivalent", swe, "kg m-2", "global-64", enc=(0.0, 1500.0), time=copy.deepcopy(t_max),
              title="Mean annual maximum snow water equivalent")
    ex.scalar("snow-cover", "snow_cover_fraction", cover, "1", "global-64", enc=(0.0, 1.0),
              time=climatology(ANNUAL_MEAN, "30-year mean of annual means"), title="Annual mean snow-cover fraction (continuous, not a mask)")
    total = precipitation_total_mm(lat, lon)
    vsm = np.where(land, np.round(np.clip(0.05 + total / 6000.0 - 0.15 * cold, 0.02, 0.5), 4), np.nan)
    ex.scalar("soil-moisture-top", "volumetric_soil_moisture", vsm, "m3 m-3", "global-64", enc=(0.0, 0.6), valid=land,
              validity_name="land", qualifiers={"depth_top_m": 0.0, "depth_bottom_m": 0.1, "frozen_water": "excluded"},
              time=climatology(ANNUAL_MEAN, "30-year mean of annual means"), title="Volumetric soil moisture, 0-0.1 m, liquid water only")
    bucket = np.where(land, np.round(np.clip(total / 2500.0, 0, 1), 4), np.nan)
    ex.scalar("bucket-index", "example:bucket_fullness_index", bucket, "1", "global-64", enc=(0.0, 1.0), valid=land,
              validity_name="land", time=climatology(ANNUAL_MEAN, "30-year mean of annual means"),
              definition="Fullness of the example generator's single-bucket hydrology model, 0 = empty, 1 = full. "
                         "A model index with no physical units or depth; it must not be interpreted as volumetric soil moisture.",
              title="Producer-specific soil bucket index (extension quantity)")
    ex.notes = [
        "snow-depth-max is physical snowpack thickness; swe-max is water equivalent; snowfall would be a separate accumulated amount.",
        "Zero snow in warm regions is a valid 0 (pixel 0), not missing.",
        "bucket-index uses the namespaced quantity 'example:bucket_fullness_index'. Generic consumers report it as 'retained'.",
    ]
    ex.write(out)


BIOMES = [
    {"code": 0, "id": "example:marine_cold", "label": "Cold marine", "color": "#1F4E79", "realm": "marine",
     "description": "Ocean with annual mean surface water below 12 degC. Code 0 is a real class."},
    {"code": 1, "id": "example:marine_warm", "label": "Warm marine", "color": "#2E86C1", "realm": "marine",
     "description": "Ocean with annual mean surface water at or above 12 degC."},
    {"code": 2, "id": "example:ice_sheet", "label": "Ice sheet", "color": "#F2F4F4", "realm": "terrestrial"},
    {"code": 3, "id": "example:tundra", "label": "Tundra", "color": "#A9CCE3", "realm": "terrestrial"},
    {"code": 4, "id": "example:boreal_forest", "label": "Boreal forest", "color": "#1E8449", "realm": "terrestrial"},
    {"code": 5, "id": "example:temperate_forest", "label": "Temperate forest", "color": "#58D68D", "realm": "terrestrial"},
    {"code": 6, "id": "example:grassland", "label": "Grassland", "color": "#D4AC0D", "realm": "terrestrial"},
    {"code": 7, "id": "example:desert", "label": "Desert", "color": "#F5CBA7", "realm": "terrestrial"},
    {"code": 8, "id": "example:tropical_rainforest", "label": "Tropical rainforest", "color": "#145A32", "realm": "terrestrial"},
    {"code": 20, "id": "example:freshwater_lake", "label": "Freshwater lake", "color": "#5DADE2", "realm": "freshwater",
     "description": "Codes need not be contiguous."},
]

ROCKS = [
    {"code": 0, "id": "example:unconsolidated_sediment", "label": "Unconsolidated sediment", "color": "#E5D3B3"},
    {"code": 1, "id": "example:granite", "label": "Granite", "color": "#C39BD3"},
    {"code": 2, "id": "example:basalt", "label": "Basalt", "color": "#4D5656"},
    {"code": 3, "id": "example:limestone", "label": "Limestone", "color": "#F7F9F9"},
    {"code": 4, "id": "example:sandstone", "label": "Sandstone", "color": "#E59866"},
    {"code": 5, "id": "example:metamorphic", "label": "Metamorphic", "color": "#7D6608"},
]


def biome_codes(lat, lon, elev):
    ocean = elev < 0
    tmean, tsea = temperature_mean_c(lat, elev)
    p = precipitation_total_mm(lat, lon)
    codes = np.full(elev.shape, 6, dtype=np.uint16)
    codes[ocean & (tsea + 1 < 12)] = 0
    codes[ocean & (tsea + 1 >= 12)] = 1
    land = ~ocean
    codes[land & (tmean < -15)] = 2
    codes[land & (tmean >= -15) & (tmean < -5)] = 3
    codes[land & (tmean >= -5) & (tmean < 3)] = 4
    codes[land & (tmean >= 3) & (tmean < 18) & (p > 700)] = 5
    codes[land & (tmean >= 3) & (p < 250)] = 7
    codes[land & (tmean >= 20) & (p > 1600)] = 8
    return codes


def ex_biome_and_rock(out):
    ex = Example(
        "biome-and-rock",
        "Biome and rock classes with namespaced class tables",
        "Categorical biome (including warm and cold marine biomes) and lithology, each with an explicit class table. Code 0 is a valid class.",
    )
    lat, lon = ex.grid("global-64", 64, 32)
    elev = elevation_field(lat, lon)
    codes = biome_codes(lat, lon, elev)
    codes[9:11, 36:38] = np.where(elev[9:11, 36:38] >= 0, 20, codes[9:11, 36:38])
    ex.class_table("example-biomes", "example:biomes-v1", BIOMES, title="Example biome taxonomy v1",
                   description="Producer taxonomy. Marine biomes are kept as marine classes, not mapped to terrestrial ones.")
    ex.class_table("example-rocks", "example:rock-types-v1", ROCKS, title="Example surface rock types v1")
    ex.categorical("biome", "biome", codes, "global-64", "example-biomes",
                   source={"width": 256, "height": 128, "resampling": "mode",
                           "description": "Computed at 256x128 and reduced by majority vote; class codes are never interpolated."})
    ocean = elev < 0
    rock = np.where(ocean, np.where(np.cos(3 * lon) > 0.2, 2, 0),
                    (np.floor((np.sin(4 * lon) + np.cos(5 * lat) + 2) * 1.5).astype(int) % 5) + 1).astype(np.uint16)
    ex.categorical("lithology", "lithology", rock, "global-64", "example-rocks", qualifiers={"level": "surface"})
    palette = {c["code"]: hex_to_rgb(c["color"]) for c in BIOMES}
    preview = np.zeros(codes.shape + (3,), dtype=np.uint8)
    for code, rgb in palette.items():
        preview[codes == code] = rgb
    ex.reference("biome-preview", preview, "preview", "registered", grid="global-64", depicts=["biome"],
                 title="Biome colours from the class table (visual reference only)")
    key = np.zeros((16 * len(BIOMES), 32, 3), dtype=np.uint8)
    for i, c in enumerate(BIOMES):
        key[i * 16 : (i + 1) * 16] = hex_to_rgb(c["color"])
    ex.reference("biome-colour-key", key, "colour_key", "unregistered", depicts=["biome"],
                 title="Colour swatches in class-table order (top to bottom)")
    ex.notes = [
        "Codes 0 (cold marine) and 1 (warm marine) are marine biomes in the producer's own taxonomy.",
        "Code 0 is a valid class; validity is expressed only by validity masks.",
        "Colours are optional display hints. Consumers identify classes by code and id, never by colour.",
    ]
    ex.write(out, sidecars=True)


def ex_multi_resolution(out):
    ex = Example(
        "multi-resolution",
        "Aligned grids at three resolutions",
        "Elevation at 128x64, temperature at 64x32 and precipitation at 32x16, all on the same global bounds. "
        "Elevation uses a declared non-sea-level datum.",
        calendars={"aster": ASTER},
    )
    ex.world["vertical_datums"] = {
        "reference-sphere": {
            "description": "Surface of the reference sphere of radius world.body.radius_m.",
            "sea_level_m": 120.0,
        }
    }
    lat, lon = ex.grid("g128", 128, 64)
    elev = elevation_field(lat, lon)
    ex.scalar("elevation", "elevation", elev + 120.0, "m", "g128", enc=(-8000.0, 7000.0),
              qualifiers={"datum": "reference-sphere", "coverage": "full"},
              title="Elevation above the reference sphere (sea level is +120 m on this datum)")
    lat64, lon64 = ex.grid("g64", 64, 32)
    t, _ = temperature_mean_c(lat64, elevation_field(lat64, lon64))
    ex.scalar("t-annual-mean", "air_temperature", np.round(t + 273.15, 4), "K", "g64", enc=(200.0, 320.0),
              qualifiers={"elevation_reference": "terrain"}, time=climatology(ANNUAL_MEAN, "30-year mean of annual means"),
              source={"width": 64, "height": 32, "resampling": "none", "description": "Native model resolution."},
              title="Annual mean air temperature in kelvin")
    lat128, lon128 = mesh(ex.grids["g128"])
    fine = precipitation_total_mm(lat128, lon128)
    coarse = np.round(fine.reshape(16, 4, 32, 4).mean(axis=(1, 3)), 3)
    ex.grid("g32", 32, 16)
    ex.scalar("precip-annual", "precipitation_amount", coarse, "kg m-2", "g32", enc=(0.0, 4000.0),
              time=climatology(ANNUAL_TOTAL, "30-year mean of annual totals"),
              source={"width": 128, "height": 64, "resampling": "area_mean", "description": "4x4 block mean of a 128x64 field."},
              title="Mean annual precipitation in kg m-2")
    ex.notes = [
        "All three grids share bounds, so their pixel edges nest (128 = 2 x 64 = 4 x 32).",
        "Elevation relative to sea level = value - 120 m. The derived sea-level pixel is floor((120+8000)/15000*65535 + 0.5) = "
        f"{int(scalarmod.encode([120.0], -8000.0, 7000.0)[0])}.",
        "precip-annual records its source resolution (128x64) and resampling (area_mean) separately from the delivered 32x16 grid.",
    ]
    ex.write(out)


def ex_regional_seam(out):
    ex = Example(
        "regional-seam",
        "Regional grid crossing the antimeridian",
        "A 60 x 40 degree region from 160E eastwards across 180 to 140W, with 1-degree pixels.",
        calendars={"aster": ASTER},
    )
    lat, lon = ex.grid("pacific-strip", 60, 40, west=160.0, east=220.0, north=30.0, south=-10.0,
                       description="East bound 220 means 140W; the region crosses the antimeridian at column 20.")
    elev = elevation_field(lat, lon)
    ex.scalar("elevation", "elevation", elev, "m", "pacific-strip", enc=(-8000.0, 6000.0),
              qualifiers={"datum": "sea_level", "coverage": "full"}, samples=[(0, 19), (0, 20), (39, 59)])
    t, _ = temperature_mean_c(lat, elev)
    ex.scalar("t-annual-mean", "air_temperature", np.round(t, 4), "degC", "pacific-strip", enc=(-60.0, 50.0),
              qualifiers={"elevation_reference": "terrain"}, time=climatology(ANNUAL_MEAN, "30-year mean of annual means"),
              samples=[(0, 19), (0, 20)])
    ex.notes = [
        "Column 19 centre is 179.5E and column 20 centre is 179.5W (-179.5): adjacent columns across the antimeridian.",
        "The grid does not wrap: its longitude span is 60 degrees, not 360.",
        "lon values in samples are normalised to [-180, 180).",
    ]
    ex.write(out)


def ex_missing_and_zero(out):
    ex = Example(
        "missing-and-zero",
        "Missing values versus legitimate zeros",
        "Validity masks mark missing data. Pixel 0 can be a real value or a real class, and an entirely missing layer is explicit.",
        calendars={"aster": ASTER},
    )
    lat, lon = ex.grid("global-32", 32, 16)
    total = precipitation_total_mm(lat, lon)
    total[6:10, 4:10] = 0.0
    valid = np.ones(total.shape, bool)
    valid[2:5, 20:28] = False
    ex.scalar("precip-annual", "precipitation_amount", np.where(valid, total, np.nan), "mm", "global-32", enc=(0.0, 4000.0),
              valid=valid, validity_name="survey-coverage", time=climatology(ANNUAL_TOTAL, "30-year mean of annual totals"),
              samples=[(7, 5), (3, 22)], title="Precipitation with a desert of exact zeros and a missing patch")
    cover = np.where(np.abs(lat) > 1.0, 2, np.where(total == 0.0, 0, 1)).astype(np.uint16)
    ex.class_table("example-cover", "example:land-cover-v1", [
        {"code": 0, "id": "example:bare_ground", "label": "Bare ground", "color": "#C8B482"},
        {"code": 1, "id": "example:vegetated", "label": "Vegetated", "color": "#3C8C3C"},
        {"code": 2, "id": "example:permanent_ice", "label": "Permanent ice", "color": "#F0F0F0"},
    ])
    ex.categorical("land-cover", "land_cover", np.where(valid, cover, 0), "global-32", "example-cover", valid=valid,
                   samples=[(7, 5), (3, 22)])
    ex.files.pop("masks/land-cover-valid.png")
    ex.layers[-1]["validity_mask"]["path"] = "masks/survey-coverage.png"
    nothing = np.zeros(total.shape, bool)
    ex.scalar("snow-depth-max", "snow_depth", np.full(total.shape, np.nan), "m", "global-32", enc=(0.0, 5.0), valid=nothing,
              validity_name="nothing-valid", time=climatology(MEAN_ANNUAL_MAX, "30-year mean of annual maxima"),
              title="Entirely missing layer (all samples invalid)",
              description="Included to demonstrate explicit total absence; producers may instead omit such layers.")
    ex.notes = [
        "precip-annual row 7 col 5 is a valid 0 mm (pixel 0); row 3 col 22 is invalid (also pixel 0, but masked).",
        "land-cover code 0 'bare ground' is a real class; invalid samples are identified by the shared validity mask.",
        "snow-depth-max has valid_count 0 and no minimum/maximum statistics.",
    ]
    ex.write(out)


def ex_constant_fields(out):
    ex = Example(
        "constant-fields",
        "Constant fields",
        "Constant values are encoded with encoding.min equal to the value, so every pixel is 0 and decodes exactly.",
    )
    ex.grid("global-32", 32, 16)
    shape = (16, 32)
    ex.scalar("elevation", "elevation", np.full(shape, 250.0), "m", "global-32", enc=(250.0, 251.0),
              qualifiers={"datum": "sea_level", "coverage": "full"}, title="Flat plateau at 250 m")
    lo, hi = scalarmod.choose_range(np.full(shape, -5.0))
    ex.scalar("t-snapshot", "air_temperature", np.full(shape, -5.0), "degC", "global-32", enc=(lo, hi),
              qualifiers={"elevation_reference": "terrain"}, title="Uniform -5 degC snapshot")
    ex.mask("ocean", "ocean_mask", np.zeros(shape, bool), "global-32", title="No ocean anywhere (all 0)")
    ex.notes = [
        "encoding.min < encoding.max is always required, even for constant fields.",
        f"The reference helper choose_range picks ({lo}, {hi}) for a constant -5.",
    ]
    ex.write(out)


# ------------------------------------------------------------------ invalid examples


def base_invalid(name, title):
    ex = Example(name, title, "Deliberately invalid example. See examples/invalid/expectations.json.", calendars={"aster": ASTER})
    lat, lon = ex.grid("tiny", 16, 8)
    elev = elevation_field(lat, lon)
    t, _ = temperature_mean_c(lat, elev)
    ex.scalar("t-annual-mean", "air_temperature", np.round(t, 3), "degC", "tiny", enc=(-60.0, 50.0),
              qualifiers={"elevation_reference": "terrain"}, time=climatology(ANNUAL_MEAN, "annual mean"), statistics=False)
    return ex, lat, lon, elev


EXPECTATIONS: dict = {}


def write_invalid(out, ex, codes, reason, **kw):
    ex.write(out, expected=False, **kw)
    EXPECTATIONS[ex.name] = {"target": ex.name, "error_codes": codes, "reason": reason}


def layer_by_id(manifest, lid):
    return next(layer for layer in manifest["layers"] if layer["id"] == lid)


def invalid_examples(out):
    ex, *_ = base_invalid("dimension-mismatch", "PNG size does not match its grid")
    def m(man, files):
        man["grids"]["tiny"]["width"] = 20
    write_invalid(out, ex, ["dimension.mismatch"], "The grid declares 20x8 but the PNG is 16x8.", mutate_before_hash=m)

    ex, lat, lon, elev = base_invalid("unknown-class-code", "Categorical pixel uses an undeclared code")
    ex.class_table("cls", "example:tiny-classes", [
        {"code": 0, "id": "example:ocean", "label": "Ocean"},
        {"code": 1, "id": "example:land", "label": "Land"},
        {"code": 2, "id": "example:ice", "label": "Ice"},
    ])
    codes = np.where(elev < 0, 0, 1).astype(np.uint16)
    codes[4, 4] = 7
    ex.categorical("biome", "biome", codes, "tiny", "cls")
    write_invalid(out, ex, ["class.unknown_code"], "Pixel (4, 4) has code 7, which is not in the class table.")

    ex, *_ = base_invalid("inconsistent-units", "Temperature declared in millimetres")
    write_invalid(out, ex, ["units.incompatible"], "air_temperature must use K or degC; 'mm' is a length.",
                  mutate_before_hash=lambda man, f: layer_by_id(man, "t-annual-mean").update(units="mm"))

    ex, lat, lon, elev = base_invalid("amount-with-mean-aggregation", "Accumulated amount described as a mean rate")
    ex.scalar("precip", "precipitation_amount", precipitation_total_mm(lat, lon), "mm", "tiny", enc=(0.0, 4000.0),
              time=climatology(ANNUAL_MEAN, "annual mean"), statistics=False)
    write_invalid(out, ex, ["semantics.accumulation"],
                  "precipitation_amount must start with a sum; a mean over timesteps describes a rate (use precipitation_rate).")

    ex, *_ = base_invalid("temperature-without-elevation-reference", "Temperature missing terrain/sea-level qualifier")
    write_invalid(out, ex, ["qualifiers.invalid"], "air_temperature requires qualifiers.elevation_reference.",
                  mutate_before_hash=lambda man, f: layer_by_id(man, "t-annual-mean").pop("qualifiers"))

    ex, lat, lon, elev = base_invalid("incomplete-aggregation", "Aggregation leaves a dimension unreduced")
    def m(man, files):
        layer_by_id(man, "t-annual-mean")["time"]["aggregation"] = [{"statistic": "mean", "over": "timesteps", "within": "period"}]
    write_invalid(out, ex, ["time.aggregation_incomplete"],
                  "A mean within each period of each year leaves year and period dimensions; a final reduction is missing.",
                  mutate_before_hash=m)

    ex, *_ = base_invalid("missing-grid-reference", "Layer refers to an undeclared grid")
    write_invalid(out, ex, ["reference.missing"], "The layer uses grid 'not-declared'.",
                  mutate_before_hash=lambda man, f: layer_by_id(man, "t-annual-mean").update(grid="not-declared"))

    ex, *_ = base_invalid("missing-file", "Manifest references a file that is absent")
    write_invalid(out, ex, ["file.missing"], "maps/t-annual-mean.png is listed but not present.",
                  mutate_after_hash=lambda man, files: files.pop("maps/t-annual-mean.png"))

    ex, lat, lon, elev = base_invalid("invalid-png-depth", "Scalar layer stored as 8-bit PNG")
    def m(man, files):
        files["maps/t-annual-mean.png"] = pngmod.write_png(np.zeros((8, 16), np.uint8), 8)
    write_invalid(out, ex, ["png.type"], "Scalar layers must be 16-bit greyscale; this one is 8-bit.", mutate_before_hash=m)

    ex, *_ = base_invalid("png-transparency", "Data PNG with a tRNS chunk")
    def m(man, files):
        files["maps/t-annual-mean.png"] = pngmod.insert_chunk(files["maps/t-annual-mean.png"], "tRNS", b"\x00\x00")
    write_invalid(out, ex, ["png.transparency"], "tRNS would imply transparency-based validity; use a validity mask.",
                  mutate_before_hash=m)

    ex, *_ = base_invalid("bad-hash", "SHA-256 does not match the file")
    def m(man, files):
        layer_by_id(man, "t-annual-mean")["sha256"] = "0" * 64
    write_invalid(out, ex, ["hash.mismatch"], "The declared SHA-256 is all zeros.", mutate_after_hash=m)

    ex, *_ = base_invalid("inverted-encoding-range", "encoding.min greater than encoding.max")
    def m(man, files):
        layer_by_id(man, "t-annual-mean")["encoding"].update({"min": 50.0, "max": -60.0})
    write_invalid(out, ex, ["encoding.range"], "encoding.min must be strictly less than encoding.max.", mutate_before_hash=m)

    ex, lat, lon, elev = base_invalid("mask-not-binary", "Binary mask containing intermediate values")
    ex.mask("ocean", "ocean_mask", elev < 0, "tiny")
    def m(man, files):
        arr = np.where(elev < 0, 255, 0).astype(np.uint8)
        arr[0, :4] = 128
        files["maps/ocean.png"] = pngmod.write_png(arr, 8)
    write_invalid(out, ex, ["mask.values"], "Binary masks may contain only 0 and 255; this one contains 128.", mutate_before_hash=m)

    ex, lat, lon, elev = base_invalid("interpolated-class-codes", "Categorical layer resampled bilinearly")
    ex.class_table("cls", "example:tiny-classes", [{"code": 0, "id": "example:ocean", "label": "Ocean"},
                                                   {"code": 1, "id": "example:land", "label": "Land"}])
    ex.categorical("cover", "land_cover", np.where(elev < 0, 0, 1), "tiny", "cls",
                   source={"width": 64, "height": 32, "resampling": "bilinear"})
    write_invalid(out, ex, ["resampling.invalid_for_kind"], "Class codes cannot be interpolated.")

    ex, *_ = base_invalid("seam-bounds-reversed", "Antimeridian crossing written with east < west")
    def m(man, files):
        man["grids"]["tiny"]["bounds"].update({"west": 170.0, "east": -170.0})
    write_invalid(out, ex, ["grid.bounds"], "Write a 170E..170W region as west 170, east 190.", mutate_before_hash=m)

    ex, *_ = base_invalid("sidecar-mismatch", "Sidecar disagrees with the manifest")
    def m(man, files):
        side = json.loads(files["maps/t-annual-mean.png.json"])
        side["layer"]["encoding"]["max"] = 40.0
        files["maps/t-annual-mean.png.json"] = dump_json(side).encode()
    write_invalid(out, ex, ["sidecar.mismatch"], "The sidecar copy changes encoding.max; the manifest is authoritative.",
                  sidecars=True, mutate_after_hash=m)

    ex, lat, lon, elev = base_invalid("statistics-inconsistent", "Declared statistics contradict the data")
    def m(man, files):
        layer_by_id(man, "t-annual-mean")["statistics"] = {"minimum": -59.0, "maximum": 49.0}
    write_invalid(out, ex, ["statistics.inconsistent"], "Observed extrema must agree with decoded data within half a step.",
                  mutate_before_hash=m)

    ex, lat, lon, elev = base_invalid("reference-only", "Only a preview image, no data")
    ex.layers.clear()
    ex.files.clear()
    ex.reference("preview", hypsometric(elev), "preview", "registered", grid="tiny")
    write_invalid(out, ex, ["package.no_data_layers"], "A reference image does not substitute for numeric data.")

    ex, lat, lon, elev = base_invalid("unknown-quantity", "Unnamespaced quantity not in the registry")
    def m(man, files):
        layer_by_id(man, "t-annual-mean")["quantity"] = "temperature"
    write_invalid(out, ex, ["quantity.unknown"], "'temperature' is not a registry id; use air_temperature or a namespaced extension.",
                  mutate_before_hash=m)

    ex, lat, lon, elev = base_invalid("extension-without-definition", "Extension quantity lacks a definition")
    ex.scalar("idx", "example:moisture_index", np.clip(precipitation_total_mm(lat, lon) / 3000, 0, 1), "1", "tiny",
              enc=(0.0, 1.0), statistics=False)
    write_invalid(out, ex, ["quantity.definition_missing"], "Namespaced quantities must say what their values mean.")

    # Archive-level failures
    zips = out / "_archives"
    good = base_invalid("archive-source", "Otherwise valid package used to build the archive cases")[0]
    src = good.write(zips, expected=False)

    def zip_case(name, entries, codes, reason, symlink=None):
        with zipfile.ZipFile(out / f"{name}.zip", "w") as zf:
            for entry_name, data in entries:
                info = zipfile.ZipInfo(entry_name, date_time=(1980, 1, 1, 0, 0, 0))
                info.external_attr = 0o100644 << 16
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    zf.writestr(info, data)
            if symlink:
                link = zipfile.ZipInfo(symlink[0], date_time=(1980, 1, 1, 0, 0, 0))
                link.external_attr = 0o120777 << 16
                link.create_system = 3
                zf.writestr(link, symlink[1])
        EXPECTATIONS[name] = {"target": f"{name}.zip", "error_codes": codes, "reason": reason}

    base_entries = [(rel.as_posix(), (src / rel).read_bytes()) for rel in
                    sorted(p.relative_to(src) for p in src.rglob("*") if p.is_file())]
    zip_case("unsafe-archive-path", base_entries + [("../escape.png", b"not extracted")], ["archive.unsafe_path"],
             "The archive contains '../escape.png', which would escape an extraction directory.")
    zip_case("absolute-archive-path", base_entries + [("/tmp/absolute.png", b"x"), ("C:/absolute.png", b"x")],
             ["archive.unsafe_path"], "Archive entries must be relative; absolute and drive-letter paths are rejected.")
    zip_case("duplicate-archive-entry", base_entries + [("maps/t-annual-mean.png", b"second copy")], ["archive.duplicate_entry"],
             "Two entries share one name, so readers could disagree about which is authoritative.")
    zip_case("manifest-not-at-root", [("bundle/" + n, d) for n, d in base_entries], ["manifest.missing"],
             "Everything sits inside a 'bundle/' folder; manifest.json must be at the archive root.")
    zip_case("symlink-archive-entry", base_entries, ["archive.symlink"], "Symlink entries are rejected rather than followed.",
             symlink=("maps/link.png", "../../outside.png"))
    shutil.rmtree(zips)
    (out / "expectations.json").write_text(dump_json(dict(sorted(EXPECTATIONS.items()))), encoding="utf-8", newline="\n")


# ------------------------------------------------------------------ driver

VALID = [ex_elevation_bathymetry, ex_climate_only, ex_snow_and_soil, ex_biome_and_rock, ex_multi_resolution,
         ex_regional_seam, ex_missing_and_zero, ex_constant_fields]


def generate(root: Path) -> None:
    EXPECTATIONS.clear()
    for sub in ("valid", "invalid", "packed", "expected"):
        shutil.rmtree(root / sub, ignore_errors=True)
    for fn in VALID:
        fn(root / "valid")
    invalid_examples(root / "invalid")
    (root / "packed").mkdir(parents=True, exist_ok=True)
    pack(root / "valid" / "climate-only", root / "packed" / "climate-only.zip")
    pack(root / "valid" / "elevation-bathymetry", root / "packed" / "elevation-bathymetry.zip")
    write_expected_md(root)


def write_expected_md(root: Path) -> None:
    lines = [
        "# Expected decoded values",
        "",
        "Generated by `scripts/generate_examples.py`; do not edit by hand. `examples/expected/<name>.json` holds the same",
        "data in machine-readable form. Scalar values are the pre-encoding values; a conforming decoder must reproduce them within",
        "the stated tolerance (half of one quantisation step). Rows count from the north edge, columns from the west edge, both 0-based.",
        "",
    ]
    for d in sorted((root / "valid").iterdir()):
        doc = json.loads((root / "expected" / f"{d.name}.json").read_text(encoding="utf-8"))
        lines += [f"## {d.name}", "", doc["title"], ""]
        for note in doc["notes"]:
            lines.append(f"- {note}")
        lines += ["", "| layer | row | col | lat | lon | expected | pixel | tolerance |", "|---|---|---|---|---|---|---|---|"]
        for s in doc["samples"]:
            lat = s.get("lat", "")
            lon = s.get("lon", "")
            if not s["valid"]:
                val, pix, tol = "invalid", "", ""
            elif "value" in s:
                val, pix, tol = f"{s['value']:.6g} {s['units']}", str(s["pixel"]), f"{s['tolerance']:.3g}"
            elif "code" in s:
                val, pix, tol = f"code {s['code']} ({s['class_id']})", str(s["code"]), "exact"
            else:
                val, pix, tol = ("true" if s["mask"] else "false"), ("255" if s["mask"] else "0"), "exact"
            lines.append(f"| {s['layer']} | {s['row']} | {s['col']} | {lat} | {lon} | {val} | {pix} | {tol} |")
        lines.append("")
    (root / "EXPECTED.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def _strip_hashes(obj):
    if isinstance(obj, dict):
        return {k: _strip_hashes(v) for k, v in obj.items() if k != "sha256"}
    if isinstance(obj, list):
        return [_strip_hashes(v) for v in obj]
    return obj


def compare(a: Path, b: Path) -> list[str]:
    problems = []
    fa = sorted(p.relative_to(a).as_posix() for p in a.rglob("*") if p.is_file())
    fb = sorted(p.relative_to(b).as_posix() for p in b.rglob("*") if p.is_file())
    if fa != fb:
        problems.append(f"file lists differ: only committed {sorted(set(fa) - set(fb))}, only regenerated {sorted(set(fb) - set(fa))}")
    for rel in sorted(set(fa) & set(fb)):
        pa, pb = a / rel, b / rel
        if rel.endswith(".json"):
            if _strip_hashes(json.loads(pa.read_text("utf-8"))) != _strip_hashes(json.loads(pb.read_text("utf-8"))):
                problems.append(f"{rel}: JSON content differs")
        elif rel.endswith(".png"):
            da, db = pa.read_bytes(), pb.read_bytes()
            if da != db:
                try:
                    if not np.array_equal(pngmod.decode_pixels(da), pngmod.decode_pixels(db)):
                        problems.append(f"{rel}: pixels differ")
                except pngmod.PngError:
                    problems.append(f"{rel}: bytes differ")
        elif rel.endswith(".zip"):
            with zipfile.ZipFile(pa) as za, zipfile.ZipFile(pb) as zb:
                if za.namelist() != zb.namelist():
                    problems.append(f"{rel}: entries differ")
        elif rel.endswith(".md"):
            if pa.read_text("utf-8") != pb.read_text("utf-8"):
                problems.append(f"{rel}: text differs")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="regenerate into a temporary directory and compare")
    args = ap.parse_args()
    examples = ROOT / "examples"
    if not args.check:
        generate(examples)
        print(f"Examples written to {examples}")
        return 0
    with tempfile.TemporaryDirectory() as tmp:
        regen = Path(tmp) / "examples"
        generate(regen)
        problems = []
        for sub in ("valid", "invalid", "packed", "expected"):
            problems += [f"{sub}/{p}" for p in compare(examples / sub, regen / sub)]
        if (examples / "EXPECTED.md").read_text("utf-8") != (regen / "EXPECTED.md").read_text("utf-8"):
            problems.append("EXPECTED.md differs")
    if problems:
        print("Committed examples are out of date:\n  " + "\n  ".join(problems))
        print("Run: uv run python scripts/generate_examples.py")
        return 1
    print("Committed examples match the generator.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
